drivers: usb: dwc3: Remove unused force-gen1
../../../../../../kernel/motorola/sm8475/drivers/usb/dwc3/dwc3-msm-core.c:5719:8: error: no member named 'force_gen1' in 'struct dwc3_msm'
 5719 |         mdwc->force_gen1 = of_property_read_bool(node, "qcom,force-gen1");
      |         ~~~~  ^